conference/conference/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from registration.sitemaps import EventSitemap, StaticViewSitemap, PublicationSitemap


from registration import views as custom_views
from registration import views
from registration.views import index, create_profile, user_profile

sitemaps = {
    'events': EventSitemap,
    'static': StaticViewSitemap,
    'publications': PublicationSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('create-profile/', create_profile,name='create_profile'),
    path('event/', include(('registration.urls', 'registration'), namespace='registration')),

    path('profile/', views.user_profile, name='user_profile'),

    #universal login system
    path('accounts/login/', custom_views.user_login, name='login'),  # Universal login
    path('accounts/logout/', custom_views.user_logout, name='logout'),  # Universal logout
    path('accounts/password_change/', custom_views.CustomPasswordChangeView.as_view(), name='password_change'),  # Universal password change
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),  # Universal password change done
    path('accounts/password_reset/', custom_views.CustomPasswordResetView.as_view(), name='password_reset'),  # Universal password reset
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),  # Universal password reset done
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url=reverse_lazy('password_reset_complete')), name='password_reset_confirm'),  # Universal password reset confirm
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),  # Universal password reset complete
    #Bkash Payment Urls
    # path('initiate-payment/<int:event_id>/', initiate_payment, name='initiate_payment'),
    # path('payment-success/', payment_success, name='payment_success'),
    # path('payment-failure/', payment_failure, name='payment_failure'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # New Lines
from django.contrib import admin
from django.urls import path, include, reverse_lazy, re_path #  re_path is new added
from django.views.static import serve # new line
from django.contrib.auth import views as auth_views
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView
from registration.sitemaps import EventSitemap, StaticViewSitemap, PublicationSitemap


from registration import views as custom_views
from registration import views
from registration.views import index, create_profile, user_profile

sitemaps = {
    'events': EventSitemap,
    'static': StaticViewSitemap,
    'publications': PublicationSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('create-profile/', create_profile,name='create_profile'),
    path('event/', include(('registration.urls', 'registration'), namespace='registration')),

    path('profile/', views.user_profile, name='user_profile'),

    #universal login system
    path('accounts/login/', custom_views.user_login, name='login'),  # Universal login
    path('accounts/logout/', custom_views.user_logout, name='logout'),  # Universal logout
    path('accounts/password_change/', custom_views.CustomPasswordChangeView.as_view(), name='password_change'),  # Universal password change
    path('accounts/password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'), name='password_change_done'),  # Universal password change done
    path('accounts/password_reset/', custom_views.CustomPasswordResetView.as_view(), name='password_reset'),  # Universal password reset
    path('accounts/password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'), name='password_reset_done'),  # Universal password reset done
    path('accounts/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url=reverse_lazy('password_reset_complete')), name='password_reset_confirm'),  # Universal password reset confirm
    path('accounts/reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'), name='password_reset_complete'),  # Universal password reset complete
    #Bkash Payment Urls
    # path('initiate-payment/<int:event_id>/', initiate_payment, name='initiate_payment'),
    # path('payment-success/', payment_success, name='payment_success'),
    # path('payment-failure/', payment_failure, name='payment_failure'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    # for media and static files on server
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)




'''

conference/registration/urls.py
from django.conf import settings
from django.urls import path, reverse_lazy
from django.conf.urls.static import static
from . import views
from django.contrib.auth import views as auth_views
from .views import *

app_name = 'registration'  # Define app_name

# Update URL pattern
urlpatterns = [
    # URL patterns for the app.
    # path('', views.index, name='index'),  # Path for index view
    path('<int:event_id>/home/', views.home, name='home'),  # Ensure this path is correct

    # urls for events
    path('<int:event_id>/participants/', views.participant_list, name='participant_list'),
    path('<int:event_id>/participants/partial/', views.participant_list_partial, name='participant_list_partial'),

    path('<int:event_id>/participant_list/', views.participant_list, name='participant_list'),
    path('<int:event_id>/about/', views.about, name='about'),
    path('<int:event_id>/speakers/', views.speakers, name='speakers'),
    path('<int:event_id>/registration/', views.registration, name='registration'),
    path('<int:event_id>/registration_submitted/', views.registration_submitted, name='registration_submitted'),
    path('<int:event_id>/abstract_submission/', views.abstract_submission, name='abstract_submission'),
    # path('<int:event_id>/registration_message/', views.registration_message, name='registration_message'),
    path('<int:event_id>/submission_success/', views.submission_success, name='submission_success'),
    path('<int:event_id>/invitation/', views.invitation, name='invitation'),
    path('<int:event_id>/schedule/', views.schedule, name='schedule'),
    path('<int:event_id>/session_detail/<int:pk>/', views.session_detail, name='session_detail'),
    path('<int:event_id>/download_schedule_pdf/', views.download_schedule_pdf, name='download_schedule_pdf'),
    # path('<int:event_id>/modal_image/', views.modal_image, name='modal_image'),
    path('<int:event_id>/sponsors/', views.sponsor_list, name='sponsor_list'),
    path('<int:event_id>/publication_list/', views.publication_list, name='publication_list'),
    path('<int:event_id>/publication/<int:pub_id>/', views.publication_detail, name='publication_detail'),
    # Event Gallery url
    path('<int:event_id>/gallery/', views.event_gallery, name='event_gallery'),
    # Event Payment url
    # path('<int:event_id>/payment/<int:participant_id>/', views.payment, name='payment'),
    # Bkash Payment url
    path('<int:event_id>/payment/<int:participant_id>/', views.payment, name='payment'), 
    path('<int:event_id>/finalize-payment/<int:participant_id>/', finalize_payment, name='finalize_payment'),
    path('<int:event_id>/payment-success/<int:participant_id>/', payment_success, name='payment_success'), 
    path('<int:event_id>/payment-failure/<int:participant_id>/', payment_failure, name='payment_failure'),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

conference/templates/home.html
{% extends "gene_base.html" %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
{% comment %} <style>
    .modal {
        display: block; /* Show the modal by default */
        position: fixed; /* Stay in place */
        z-index: 50; /* Sit on top */
        left: 0;
        top: 0;
        width: 100%; /* Full width */
        height: 100%; /* Full height */
        overflow: auto; /* Enable scroll if needed */
        background-color: rgb(0,0,0); /* Fallback color */
        background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    }
    .modal-content {
        background-color: #fefefe;
        margin: 10% auto; /* 10% from the top and centered */
        padding: 20px;
        border: 1px solid #888;
        width: 80%; /* Could be more or less, depending on screen size */
    }
    .close {
        color: #aaa;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }
    .close:hover,
    .close:focus {
        color: black;
        text-decoration: none;
        cursor: pointer;
    }
</style> {% endcomment %}

 <!-- Modal Structure -->
{% comment %} <div id="myModal" class="modal">
    <div id="modal-content" hx-get="{% url 'registration:modal_image' event.id %}" hx-trigger="load" hx-target="#modal-content">
        <!-- Modal content will be loaded here via HTMX -->
    </div>
</div> {% endcomment %}

{% comment %} home page hero content {% endcomment %}
<!-- Hero Section for Desktop -->

<div class="hidden md:block relative bg-gradient-to-br from-pink-500 to-red-500 text-white {% if not event.event_hero_image %}py-0{% else %}min-h-screen{% endif %}">
    {% if event.event_hero_image %}
        <!-- Hero Image Section -->
        <div class="absolute inset-0 overflow-hidden">
            <img src="{{ event.event_hero_image.url }}" alt="Hero Image" class="w-full h-full object-cover">
        </div>
        <div class="absolute inset-0 flex justify-center items-end z-10">
            <!-- Register Button at Bottom Center -->
            <a href="{% url 'registration:registration' event.id %}" 
               class="inline-block px-8 py-3 bg-gradient-to-br from-pink-500 to-red-500 text-white rounded-lg 
                      hover:bg-blue-500 hover:text-white transition duration-300 mb-10 sm:mb-20">
                Register Now
            </a>
        </div>
    {% else %}
        <!-- Fallback Content if No Image -->
        <div class="mx-auto max-w-6xl text-center py-10">
            <h1 class="text-4xl sm:text-6xl font-extrabold mt-10">{{ event.name }} {{ event.year }}</h1>
            <p class="mt-4 text-lg">{{ event.slogan }}</p>
            <a href="{% url 'registration:registration' event.id %}" 
               class="mt-10 inline-block px-8 py-3 bg-white text-gray-900 rounded-lg 
                      hover:bg-blue-500 hover:text-white transition duration-300">
                Register Now
            </a>
        </div>
    {% endif %}
</div>

<!-- Hero Section for Mobile -->
<div class="block md:hidden relative bg-gradient-to-br from-pink-500 to-red-500 text-white pt-2">
    {% if event.event_hero_image %}
        <!-- Hero Image Section -->
        <div class="relative mx-auto max-w-full">
            <img src="{{ event.event_hero_image.url }}" alt="Hero Image" class="w-full h-auto object-contain">
        </div>
        <div class="absolute inset-0 flex justify-center items-end z-10">
            <a href="{% url 'registration:registration' event.id %}" 
               class="mt-10 inline-block px-5 py-2 bg-gradient-to-br from-pink-500 to-red-500 text-white rounded-lg 
                      hover:bg-blue-500 hover:text-white transition duration-300">
                Register Now
            </a>
        </div>
    {% else %}
        <div class="mx-auto max-w-6xl text-center py-10">
            <h1 class="text-4xl font-extrabold mt-10">Join Us for the {{ event.name }} {{ event.year }}</h1>
            <p class="mt-4 text-lg">{{ event.slogan }}</p>
            <a href="{% url 'registration:registration' event.id %}" 
               class="mt-10 inline-block px-8 py-3 bg-white text-gray-900 rounded-lg 
                      hover:bg-blue-500 hover:text-white transition duration-300">
                Register Now
            </a>
        </div>
    {% endif %}
</div>

{% comment %} home page about content {% endcomment %}

<section id="about" class="py-10">
    <div class="mx-auto max-w-full text-center px-10 items-center">
        <h2 class="text-3xl sm:text-4xl font-bold text-gray-900">{{ about_conference.title }}</h2>
        <div class="text-justify">
            <p class="mt-4 text-lg text-gray-700">{{ about_conference.description }}.</p>
        </div>
    </div>
</section>

{% comment %} home page speakers content {% endcomment %}
<section id="speakers" class="py-20 bg-gray-500">
    <div class="mx-auto max-w-6xl text-center">
        <h2 class="text-3xl sm:text-4xl font-bold text-white"><strong>Featured Speakers</strong></h2>
        <div class="flex flex-wrap justify-center gap-10 mt-8">
            {% for speaker in speakers %}
            <div class="bg-white shadow-lg rounded-lg p-6 flex flex-col items-center">
                <img src="{{ speaker.image.url }}" alt="{{ speaker.name }}" class="rounded-full w-32 h-32">
                <h3 class="mt-4 text-xl font-semibold text-center">{{ speaker.name }}</h3>
                <p class="mt-2 text-gray-600 text-center">{{ speaker.speciality }}</p>
                <p class="mt-2 text-gray-600 text-center">{{ speaker.institution }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</section>


{% comment %} home page invitations content {% endcomment %}
<div class="max-w-full py-8">
    <h2 class="text-3xl sm:text-4xl font-bold text-gray-900 text-center mb-4">Invitations</h2>
    <div class="grid grid-cols-1 sm:grid-cols-12 gap-8 px-10">
        {% for invitation in invitations %}
        <div class="sm:col-span-3 flex flex-col items-center border-t border-b border-gray-300 column-border first:border-t-0 last:border-b-0 p-4">
            <img src="{{ invitation.image.url }}" alt="{{ invitation.name }}" class="w-32 h-32 rounded-full">
            <p class="mt-2 text-xl text-center font-semibold">{{ invitation.name }}</p>
            <p class="text-sm">{{ invitation.designation }}</p>
        </div>
        <div class="sm:col-span-9 flex items-center border-t border-b border-gray-300 column-border first:border-t-0 last:border-b-0 p-4">
            <p class="text-justify">{{ invitation.message }}</p>
        </div>
        {% endfor %}
    </div>
</div>

{% comment %} home page registration content {% endcomment %}
<section id="registration" class="relative bg-gradient-to-br from-pink-500 to-red-500 text-white pt-20 pb-12">
    <div class="mx-auto max-w-6xl text-center">
        <h2 class="text-3xl sm:text-4xl font-bold text-white-900">Register Now</h2>
        <p class="mt-4 text-lg text-white-700">Secure your spot for the conference today.</p>
        <a href="{% url 'registration:registration' event.id %}" class="mt-10 inline-block px-8 py-3 bg-white text-gray-900 rounded-lg hover:bg-blue-500 transition duration-300">Register Now</a>
    </div>
</section>

{% comment %} <script>
    document.addEventListener('DOMContentLoaded', function() {
        // Get the modal
        var modal = document.getElementById("myModal");

        // Wait for HTMX to finish loading the content
        document.body.addEventListener('htmx:afterRequest', function(evt) {
            if (evt.detail.target.id === 'modal-content') {
                // Get the <span> element that closes the modal
                var span = document.querySelector(".close");

                // When the user clicks on <span> (x), close the modal
                span.onclick = function() {
                    modal.style.display = "none";
                }

                // When the user clicks anywhere outside of the modal, close it
                window.onclick = function(event) {
                    if (event.target == modal) {
                        modal.style.display = "none";
                    }
                }
            }
        });
    });
</script> {% endcomment %}
{% endblock %}

conference/templates/invoice_email_template.html
<!DOCTYPE html>
<html>
<head>
    <style>
        body {
            font-family: Arial, sans-serif;
        }
    </style>
</head>
<body>
    <p>Dear {{ participant.name }},</p>
    <p>Thank you for registering for {{ event.name }}.</p>
    <p>Please find your invoice attached.</p>
    <p>Best regards,</p>
    <p>Conference Team</p>
</body>
</html>

conference/templates/login_required_message.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Attention Required!</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body>
    <div class="min-h-screen flex items-center justify-center bg-gray-900">
        <div class="bg-white p-8 rounded-lg shadow-md max-w-sm ml-5 mr-5">
            <h1 class="text-2xl font-bold text-red-600 mb-4">Attention Required!</h1>
            <p class="text-gray-700">{{ message }}</p><br>
            <a href="{% url 'login' %}" class="bg-blue-500 text-white py-1 px-4 rounded w-full mt-4 ml-auto text-center">Login</a>
            <a href="{% url 'create_profile' %}" class="bg-blue-500 text-white py-1 px-4 rounded w-full mt-4 ml-auto text-center">Create Profile</a>
           
        </div>
    </div>
</body>
</html>

conference/templates/user_profile.html
{% load static %}
{% load custom_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>User Profile</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <style>
        .menu {
            background-color: rgb(139, 144, 205); /* Maroon background color */
        }
        .abstract-table {
            width: 100%;
            border-collapse: collapse;
        }
        .abstract-table th, .abstract-table td {
            border: 1px solid #ddd;
            padding: 8px;
        }
        .abstract-table th {
            background-color: #f4f4f4;
        }
    </style>
</head>
<body class="bg-gray-100">

    <header class="bg-white shadow p-4 flex items-center justify-between">
        <!-- Logo -->
        <a href="#" class="flex items-center">
          <img src="{% static 'images/BSBCS-logo-1-1.png' %}" alt="Logo" class="h-12 w-12 mr-3">
          <span class="sr-only">Events</span>
        </a>
        <!-- Centered Title -->
        <h1 class="text-1xl md:text-sm font-bold text-center flex-grow">Welcome! <span class="text-sm">{{ user_profile.name }}</span></h1>
        <!-- Logout Button -->
        <a href="{% url 'logout' %}" class="ml-auto bg-blue-500 text-white text-sm px-3 py-1 rounded hover:bg-blue-600 transition duration-200">Logout</a>
      </header>
      
      
      

<div class="container mx-auto my-8 px-4">
    <div class="flex flex-col md:flex-row bg-white shadow-lg rounded-lg overflow-hidden">
        
        <!-- Menu Column -->
        <div class="menu md:flex md:flex-col bg-gray-200 p-4 md:w-1/4 w-full">
            <ul class="space-y-4">
                <li><a href="#overview" class="block p-2 text-white hover:bg-gray-300 rounded border-b"><strong>Overview</strong></a></li>
                <li><a href="#payment-status" class="block p-2 text-white hover:bg-gray-300 rounded border-b"><strong>Payment Status</strong></a>
                </li>                
                <li><a href="#edit-profile" class="block p-2 text-white hover:bg-gray-300 rounded border-b"><strong>Edit Profile</strong></a></li>
                <li><a href="#abstract-submission" class="block p-2 text-white hover:bg-gray-300 rounded border-b"><strong>Abstract</strong></a></li>
                {% comment %} <li><a href="#Make_payment" class="block p-2 text-white hover:bg-gray-300 rounded border-b"><strong>Payment Status</strong></a></li> {% endcomment %}
                <li><a href="#password" class="block p-2 text-white hover:bg-gray-300 rounded border-b"><strong>Change Password</strong></a></li>
                {% comment %} <li><a href="#logout" class="block p-2 text-white hover:bg-gray-300 rounded border-b"><strong>Logout</strong></a></li> {% endcomment %}
            </ul>
        </div>
        
        <!-- Content Column -->
        <div class="content p-6 md:w-3/4 w-full">
            {% if message %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded mb-4">
                {{ message }}
            </div>
            {% endif %}
            
            <!-- Overview Section -->
            <section id="overview">
                <h2 class="text-xl md:text-2xl font-bold mb-4">Overview</h2>
                <p>Welcome to your profile overview. Here you can see your event details.</p>
                <!-- Active Events -->
                <div>
                    <h2 class="text-xl font-bold mt-10 mb-4">Active Events</h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {% for event in active_events %}
                        <a href="{% url 'registration:home' event.id %}" class="block p-6 bg-white shadow-lg rounded-lg hover:bg-gray-200 transition duration-300">
                            <h2 class="text-xl font-semibold">{{ event.name }} {{ event.year }}</h2>
                            <p class="mt-2 text-gray-700">From {{ event.start_date }} to {{ event.end_date }}</p>
                            <p class="mt-2 text-gray-700">Location: {{ event.location }}</p>
                            <p class="mt-2 text-gray-700">Registration: <strong>{{ event.registration }}</strong></p>
                        </a>
                        {% empty %}
                        <p class="text-center text-gray-500 col-span-full">No active events found.</p>
                        {% endfor %}
                    </div>
                </div>

                <!-- Upcoming Events -->
                <div>
                    <h2 class="text-xl font-bold mt-10 mb-4">Upcoming Events</h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {% for event in upcoming_events %}
                        <a href="{% url 'registration:home' event.id %}" class="block p-6 bg-white shadow-lg rounded-lg hover:bg-gray-200 transition duration-300">
                            <h2 class="text-xl font-semibold">{{ event.name }} {{ event.year }}</h2>
                            <p class="mt-2 text-gray-700">From {{ event.start_date }} to {{ event.end_date }}</p>
                            <p class="mt-2 text-gray-700">Location: {{ event.location }}</p>
                            <p class="mt-2 text-gray-700">Registration: <strong>{{ event.registration }}</strong></p>
                        </a>
                        {% empty %}
                        <p class="text-center text-gray-500 col-span-full">No upcoming events found.</p>
                        {% endfor %}
                    </div>
                </div>

                <!-- Past Events -->
                <div>
                    <h2 class="text-xl font-bold mt-10 mb-4">Past Events</h2>
                    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                        {% for event in closed_events %}
                        <a href="{% url 'registration:home' event.id %}" class="block p-6 bg-white shadow-lg rounded-lg hover:bg-gray-200 transition duration-300">
                            <h2 class="text-xl font-semibold">{{ event.name }} {{ event.year }}</h2>
                            <p class="mt-2 text-gray-700">From {{ event.start_date }} to {{ event.end_date }}</p>
                            <p class="mt-2 text-gray-700">Location: {{ event.location }}</p>
                            <p class="mt-2 text-gray-700">Registration: <strong>{{ event.registration }}</strong></p>
                        </a>
                        {% empty %}
                        <p class="text-center text-gray-500 col-span-full">No past events found.</p>
                        {% endfor %}
                    </div>
                </div>
            </section>

            <!-- Payment Status Section -->
            <section id="payment-status" class="hidden">
                <h2 class="text-xl md:text-2xl font-bold mb-4">Payment Status</h2>
                {% if payment_data %}
                    <table class="abstract-table">
                        <thead>
                            <tr>
                                <th>Event</th>
                                <th>Transaction ID</th>
                                <th>Amount</th>
                                <th>Status</th>
                                <th>Updated At</th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-400 text-center">
                            {% for payment in payment_data %}
                                <tr>
                                    <td>{{ payment.event }}</td>
                                    <td>{{ payment.trxID }}</td>
                                    <td>{{ payment.amount }}</td>
                                    <td>{{ payment.status }}</td>
                                    <td>{{ payment.updated_at }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>No payment records found.</p>
                {% endif %}
            </section>

            
            <!-- Edit Profile Section -->
            <section id="edit-profile" class="hidden">
                <h2 class="text-xl md:text-2xl font-bold mb-4">Edit Profile</h2>
                <form method="POST">
                    {% csrf_token %}
                    <!-- Form Fields -->
                    <div class="mb-4">
                        <label for="name" class="block text-gray-700">Name</label>
                        <input type="text" id="name" name="name" value="{{ user_profile.name }}" class="w-full p-2 border border-gray-300 rounded">
                    </div>
                    <div class="mb-4">
                        <label for="email" class="block text-gray-700">Email</label>
                        <input type="email" id="email" name="email" value="{{ user.get_username }}" class="w-full p-2 border border-gray-300 rounded">
                    </div>
                    <div class="mb-4">
                        <label for="phone" class="block text-gray-700">Phone Number</label>
                        <input type="text" id="phone" name="phone" value="{{ user_profile.phone }}" class="w-full p-2 border border-gray-300 rounded">
                    </div>
                    <button type="submit" class="bg-blue-500 text-white px-4 py-2 rounded">Save Changes</button>
                </form>
            </section>

            <!-- Abstract Submission Section -->
            <section id="abstract-submission" class="hidden">
                <h2 class="text-xl md:text-2xl font-bold mb-4">Submitted Abstract</h2>
                {% if abstract_submissions %}
                    <table class="abstract-table">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Status</th>
                                <th>Presentation Time</th>
                            </tr>
                        </thead>
                        <tbody class="bg-white divide-y divide-gray-400 text-center">
                            {% for abstract in abstract_submissions %}
                                <tr>
                                    <td>{{ abstract.title }}</td>
                                    <td class="text-center">
                                        {% if abstract.approved_for_presentation %}
                                            Approved for Presentation
                                        {% elif abstract.approved_for_poster %}
                                            Approved for Poster
                                        {% else %}
                                            Pending
                                        {% endif %}
                                    </td>
                                    {% with schedule=program_schedules|get_by_abstract:abstract %}
                                    {% if schedule %}
                                        <td>{{ schedule.time_slots.all|join:", " }}</td>
                                    {% else %}
                                        <td>No schedule available.</td>
                                    {% endif %}
                                    {% endwith %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <p>No abstract submission found.</p>
                {% endif %}
                {% comment %} <div class="mt-4 text-center">
                    <a href="{% url 'registration:abstract_submission' event.id %}" class="inline-block bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-200">Submit Another Abstract</a>
                </div> {% endcomment %}
            </section>
            
            <!-- Change Password Section -->
            <section id="password" class="hidden">
                <h2 class="text-xl md:text-2xl font-bold mb-4">Change Password</h2>
                <a href="{% url 'password_change' %}" class="inline-block bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600 transition duration-200">Change Password</a>
            </section>
        
    </div>
</div>


<script>
    document.querySelectorAll('.menu a').forEach(link => {
        link.addEventListener('click', function(e) {
            e.preventDefault();
            document.querySelectorAll('.content section').forEach(section => {
                section.classList.add('hidden');
            });
            document.querySelector(this.getAttribute('href')).classList.remove('hidden');
        });
    });
</script>

</body>
</html>